### ISSUE TITLE
Request of the dataset

### ISSUE THREAD

**Issue by pengsida** [purvaten/FLEX#1]
Hi,

Thank you for the excellent work.
May I ask when will the dataset be released?
Thank you!

Best,
Sida

**Comment by purvaten** [comment]
Hi @pengsida we have just released the data. You can follow the instructions [here](https://github.com/purvaten/FLEX#replicagrasp-dataset).

Please let me know if you have any questions.

**Comment by pengsida** [comment]
Thank you!
