### ISSUE TITLE
Multi-gpu implementation

### ISSUE THREAD

**Issue by siddharthKatageri** [purvaten/FLEX#3]
Hi @purvaten 
I am running the code on 1 A100, and it's taking 8 mins to generate poses when the receptacle is ```receptacle_aabb_TvStnd1_Top3_frl_apartment_tvstand``` which has 656 faces. Does this look normal?

I was trying to reduce the execution time by adding multi-gpu support, but I'm unable to do it successfully. 
Once we get the model over [here](https://github.com/purvaten/FLEX/blob/ab072df14087661e0818713a16120a960f8b88f3/flex/tto/inf_opt.py#L850), I am wrapping it by torch.nn.DataParallel like so 
```
all_devices = [0,1,2,3]
model = nn.DataParallel(model, device_ids=all_devices)
```
This model will hold all the pre-trained models that we load and also the MLP which is to be trained.

However, I get this error
```
Reduced version:
File "/home/t2/FLEX/flex/tto/inf_opt.py", line 405, in gan_loss
    rh_match_loss, bm_output, rv, rf = self.get_rh_match_loss(z, transl, global_orient, w, a, extras)
File "/home/t2/FLEX/flex/tto/inf_opt.py", line 87, in get_rh_match_loss
    sbj_pose = self.gan_body.decode(z)['pose_body'].reshape(bs,-1)                                                    # (b, 63)
  File "/home/t2/FLEX/flex/models/vposer_model.py", line 126, in decode
    prec = self.decoder_net(Zin)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument mat1 in method wrapper_addmm)
```
When I check, it shows ```Zin``` device is cuda:1 and vposer's ```self.decoder_net's weights``` are in cuda:0. 
I am not able to debug why this is the case. As our ```model``` has vposer model and we are wrapping the ```model``` with DataParallel, pytorch should manage the data sharing across gpus.

Can you please add support for multi-gpu or even help me debug this? It would really help a lot!

Thanks!

**Comment by purvaten** [comment]
Hi, apologies for the late reply. Our current implementation does not support multi-GPU runs and we don't plan to add support for it anytime soon. I will let you know in case this changes.
