### ISSUE TITLE
Questions About Demo Results

### ISSUE THREAD

**Issue by zhenkirito123** [purvaten/FLEX#4]
I've run the demo provided in the code and got the results below, is this the correct behavior?
<img width="615" alt="image001" src="https://github.com/purvaten/FLEX/assets/52985206/eceafe03-2b0d-49cd-9ffd-d1dabd85320e">

**Comment by purvaten** [comment]
Hi @zhenkirito123 , this shouldn't be happening. My guess is that the poses are being generated for a different example. So, there might be a mismatch in the optimization and visualization code. Can you share the command that you ran (object name, receptacle name and orientation)?

**Comment by zhenkirito123** [comment]
Hi! I just followed the command in the README example:
```
python run.py \
--obj_name stapler \
--receptacle_name receptacle_aabb_TvStnd1_Top3_frl_apartment_tvstand \
--ornt_name all \
--gender 'female'
```
Then visualized the results using viz_results.ipynb.

**Comment by purvaten** [comment]
HI @zhenkirito123 , sorry for the late response. I just re-set up my code from scratch and re-ran the command. It works fine for me. Here is an output of what it should look like.

<img width="455" alt="Screen Shot 2024-02-02 at 6 39 18 PM" src="https://github.com/purvaten/FLEX/assets/13128829/8f4cd16a-97d9-4bd5-a09d-9cd7beb1b5fb">

I don't know why yours looks different. Are you sure you didn't change anything and the data was downloaded correctly? For reference, my starting loss was 179.63, and the ending loss was 0.031.
